# nginx, automatic reverse proxy
# ------------------------------
#
# handle its configuration using the host docker socket
# which is mounted inside the container.
#
# see github.com/jwilder/nginx-proxy
# you don't need to specify an host:container mapping for the ports
# but I prefer being able to query directly my container if needed

nginx:
    image: jwilder/nginx-proxy:latest
    volumes:
        - /var/run/docker.sock:/tmp/docker.sock
    ports:
        - "80:80"

# selfoss, a web-based rss reader
# -------------------------------
#
# use php:apache in order to be consistent regarding .htaccess
# and nginx reverse proxy

selfoss:
    build: ./selfoss
    ports:
        - "8001:80"
    environment:
        VIRTUAL_HOST: "rss.localdomain"
    volumes_from:
        - selfossdata
selfossdata:
    build: ./selfoss/
    volumes:
        - /var/www/html/data
    command: "echo selfoss data container"
